# Generated by Django 3.1.7 on 2021-02-26 14:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('cidade', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('app', models.CharField(max_length=20)),
                ('grupo', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
