# Generated by Django 3.1.7 on 2021-02-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='app',
            field=models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Telegram', 'Telegram'), ('Signal', 'Signal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
