# Generated by Django 3.1.7 on 2021-02-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210226_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='slug',
            field=models.SlugField(help_text='Preenchido automaticamente para facilitar a sua vida.'),
        ),
    ]
