# Generated by Django 3.1.7 on 2021-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210226_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='slug',
            field=models.SlugField(help_text='Preenchido automaticamente para facilitar a sua vida. Por favor não altere', unique=True),
        ),
    ]
