# Generated by Django 3.1.7 on 2021-02-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210226_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(max_length=20),
        ),
    ]
