# Generated by Django 3.1.7 on 2021-02-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210226_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
