# Generated by Django 3.1.7 on 2021-03-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210303_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(blank=True, help_text='Se preencher o cep, o endereço será preenchido automaticamente', max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(blank=True, help_text='Deverá ser preenchido automaticamente pelo cep.', max_length=100, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='np_masp',
            field=models.CharField(blank=True, help_text='Preenchimento opcional', max_length=20, null=True, verbose_name='Número de Polícia ou MASP'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
