# Generated by Django 3.1.7 on 2021-03-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210304_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='Numero',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(blank=True, help_text='Deverá ser preenchido automaticamente pelo cep.', max_length=100, null=True, verbose_name='Bairro'),
        ),
    ]
